# Generated by Django 6.1 on 2026-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStreamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('radio_name', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(help_text='Station authorization key for fetching stream AES key', max_length=128, unique=True)),
                ('aes_key_hex', models.CharField(help_text='AES-128 key in hex (32 hex characters = 16 bytes)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station Stream Key',
                'verbose_name_plural': 'Station Stream Keys',
                'ordering': ['radio_id'],
            },
        ),
    ]
