// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClDw_tOd6fqCPAdBgpPMei1WtFWnDnDh0',
    appId: '1:615367902140:web:183b53382d0f76465661b9',
    messagingSenderId: '615367902140',
    projectId: 'radiohub12',
    authDomain: 'radiohub12.firebaseapp.com',
    databaseURL: 'https://radiohub12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radiohub12.firebasestorage.app',
    measurementId: 'G-1N31Y1YDJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAI62h1xD6drEiyn8BMUbo1MQOIc_kCBE',
    appId: '1:615367902140:android:941b8364eb368b875661b9',
    messagingSenderId: '615367902140',
    projectId: 'radiohub12',
    databaseURL: 'https://radiohub12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radiohub12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufL4oseGTmDmIvv3eZ8MugDn2jtBcLPA',
    appId: '1:615367902140:ios:ae5a97fc12a8cde25661b9',
    messagingSenderId: '615367902140',
    projectId: 'radiohub12',
    databaseURL: 'https://radiohub12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radiohub12.firebasestorage.app',
    iosBundleId: 'com.example.radioadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufL4oseGTmDmIvv3eZ8MugDn2jtBcLPA',
    appId: '1:615367902140:ios:ae5a97fc12a8cde25661b9',
    messagingSenderId: '615367902140',
    projectId: 'radiohub12',
    databaseURL: 'https://radiohub12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radiohub12.firebasestorage.app',
    iosBundleId: 'com.example.radioadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClDw_tOd6fqCPAdBgpPMei1WtFWnDnDh0',
    appId: '1:615367902140:web:ded65f5fdf48be975661b9',
    messagingSenderId: '615367902140',
    projectId: 'radiohub12',
    authDomain: 'radiohub12.firebaseapp.com',
    databaseURL: 'https://radiohub12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radiohub12.firebasestorage.app',
    measurementId: 'G-JTJ578BZP3',
  );
}
